outputpath: experiments/clotho_v2/
remark: fromscratch

train_h5_csv: data/clotho_v2/dev/lms.csv
train_caption_file: data/clotho_v2/dev/text.json
val_h5_csv: data/clotho_v2/val/lms.csv
val_caption_file: data/clotho_v2/val/text.json
vocab_file: data/clotho_v2/dev/vocab.pkl
zh: False
dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
augments: [timemask, freqmask]
distributed: False

encodermodel: CNN10QEncoder
encodermodel_args: 
    embed_size: 512
decodermodel: RNNBahdanauAttnDecoder
decodermodel_args:
    embed_size: 512
    rnn_type: GRU
    num_layers: 1
    hidden_size: 512
    dropout: 0.5
model: Seq2SeqAttnModel
model_args: {}

improvecriterion: score # Can be acc | loss | score

optimizer: Adam
optimizer_args:
    lr: 0.0005
    weight_decay: 0.0
max_grad_norm: 0.5
epochs: 25
scheduler: ExponentialDecayScheduler
scheduler_args:
    linear_warmup: True
    warmup_iters: 3000
    final_lrs: !!float 5e-7
    

ss: False
ss_args:
    ss_mode: linear
    ss_ratio: 1.0
    final_ss_ratio: 0.7

label_smoothing: True
smoothing: 0.1
