outputpath: experiments/clotho

feature_file: data/clotho/logmel.hdf5
caption_file: data/clotho/dev.json
vocab_file: data/clotho/vocab.pth
zh: False
dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
#augments: [timemask, freqmask]
augments: []

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: CNN10QEncoder
encodermodel_args:
    embed_size: 512
decodermodel: RNNBahdanauAttnDecoder
decodermodel_args:
    embed_size: 256
    dropout: 0.3
    rnn_type: GRU
    num_layers: 1
    hidden_size: 512
    # attn_hidden_size: 512
model: Seq2SeqAttnModel
model_args: {}
modelwrapper: ScstWrapper

load_pretrained: True
pretrained: experiments/clotho/Seq2SeqAttnModel/2020-11-26_00-54-11_ec02e7922f3e11eb955f69e9a1a7a162/saved.pth

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
    weight_decay: 0.0
epochs: 100

