outputpath: experiments/clotho

#feature_stream: copy-feats scp:data/clotho/logmel_dev.scp ark:- |
feature_file: data/clotho/logmel.hdf5
caption_file: data/clotho/dev.json
vocab_file: data/clotho/vocab.pth
zh: False
dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
#augments: [timemask, freqmask]
augments: []

scaler: StandardScaler # Can be any of sklearn.preprocessing that supports fit_partial
scaler_args:
    with_std : True
    with_mean : True        

encodermodel: CNN10QEncoder
encodermodel_args:
    num_layers: 1
    dropout: 0.0
    # Enables the passing of the hidden encoder state to the decoder
    use_hidden: True
    # Can be time, mean ( for last timestep, mean reduction)
    representation: mean
    hidden_size: 512
decodermodel: RNNDecoder
decodermodel_args:
    num_layers: 1
    hidden_size: 512
    #attn_hidden_size: 512
basemodel: CaptionModel
basemodel_args:
    embed_size: 512
    dropout: 0.3
modelwrapper: ScstWrapper

load_pretrained: True
pretrained: experiments/clotho/CaptionModel/pretrainCNN10Q/saved.pth

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
    weight_decay: 0.0
epochs: 100

